version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: chat_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
      MONGO_INITDB_DATABASE: chatapp
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
